version: 0.2

env:
  variables:
    APP_SYNC_API_KEY: "da2-rlau7flfyvgl7laobgqdkn3f2e"

phases:
  preBuild:
    commands:
      - echo "Setting up API Key"
  build:
    commands:
      - echo Build started on `date`
      - npm install
      - npm run build
artifacts:
  baseDirectory: build
  files:
    - "**/*"
